name: Generate Podcast Feeds

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout Repo
        uses: actions/checkout@v4.1.2
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-verson: '3.10'
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python3 feed.py
      - name: Push repo
        run: | 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Modified Feed"
          git push
        
        
         
       
        
      

