name: Generate Podcast Feeds

on: [push]
jobs:
  update_feed:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout Repo
        uses: actions/checkout@v4.1.2
      - name: Run Feed Generator
        uses: GeluKu/podcast-generator-g@main
